language: python
python:
  - '3.6'

# safelist
branches:
  only:
    - py10

# dist: xenial

services:
  - postgresql

addons:
  chrome: stable

env: DJANGO_SETTINGS_MODULE="opynfact_web_project.settings.ci_travis"

before_install:
  - pip install -r requirements_origin.txt
  - pip freeze > requirements.txt
  
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 https://www.chromestatus.com & # http://localhost &

before_script:
  - PLATFORM=linux64
  - VERSION=$(curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
  - curl http://chromedriver.storage.googleapis.com/$VERSION/chromedriver_$PLATFORM.zip | bsdtar -xvf - -C env/bin/
  - chromedriver
  - ll -a ./env/bin/

# before_script:
  # - psql -c 'create database travis_ci_test;' -U postgres
  # python manage.py migrate

  # - python manage.py initializedatabase 0
script:
  python manage.py collectstatic <<< yes
  # python manage.py createsuperuser
  
  # pytest -s -Wa [--exitfirst] [--reuse-db] -vv --cov=./ --cov-report html
  # pytest -s -Wa -vv --cov=./ --cov-report html

