language: python
python:
  - '3.6'

# safelist
branches:
  only:
    - py10

before_install:
  - pip install -r requirements_origin.txt

env: DJANGO_SETTINGS_MODULE="opynfact_web_project.settings"

services:
  - postgresql

script:
  # - ./manage.py test
  # pytest -s -Wa [--exitfirst] [--reuse-db] -vv --cov=./ --cov-report html
  pytest -s -Wa -vv --cov=./ --cov-report html