language: python
python:
  - '3.6'

# safelist
branches:
  only:
    - py10

# dist: xenial

addons:
  chrome: stable

before_install:
  - pip install -r requirements_origin.txt
  - pip freeze > requirements.txt
  
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --dump-dom --remote-debugging-port=9222 https://www.chromestatus.com/ # http://localhost &


env: DJANGO_SETTINGS_MODULE="opynfact_web_project.settings.ci_travis"

services:
  - postgresql

# before_script:
  # - psql -c 'create database travis_ci_test;' -U postgres
  # python manage.py migrate

  # - python manage.py initializedatabase 0
script:
  python manage.py collectstatic <<< yes
  # python manage.py createsuperuser
  
  # pytest -s -Wa [--exitfirst] [--reuse-db] -vv --cov=./ --cov-report html
  # pytest -s -Wa -vv --cov=./ --cov-report html

